//! Raw FFI bindings to [libnghttp3](https://nghttp2.org/nghttp3/), the HTTP/3
//! framing and QPACK library from the ngtcp2 project.
//!
//! The native library is compiled from the packaged `vendor/nghttp3` git submodule by this
//! crate's build script (lib-only, static). The bindings below are generated by
//! `bindgen` at build time, so they always match the vendored headers.
//!
//! nghttp3 implements HTTP/3 message framing and QPACK only. It depends on no
//! QUIC transport and no TLS library, and this crate adds neither: driving a
//! connection means feeding it bytes that arrived on a QUIC stream and writing
//! back the bytes it produces.
//!
//! This is an unsafe, unopinionated `-sys` crate: it exposes the C API as-is.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(rustdoc::broken_intra_doc_links)]
// nghttp3's own doxygen comments cite RFCs as bare URLs, and bindgen carries them through
// verbatim. Rewriting generated documentation to satisfy a lint would mean post-processing
// the bindings, which is a far worse trade than allowing the lint here.
#![allow(rustdoc::bare_urls)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
