//! Raw FFI bindings to [libnghttp2](https://nghttp2.org).
//!
//! The native library is compiled from the `deps/nghttp2` git submodule by this
//! crate's build script (lib-only, static). The bindings below are generated by
//! `bindgen` at build time, so they always match the vendored headers.
//!
//! This is an unsafe, unopinionated `-sys` crate: it exposes the C API as-is.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(rustdoc::broken_intra_doc_links)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
