#ifndef NGNET_H3_SYS_WRAPPER_H
#define NGNET_H3_SYS_WRAPPER_H

/* `version.h` is generated by CMake from `version.h.in`, so it exists only in
   the install tree. The build script points bindgen at the install include
   directory rather than at the source checkout for exactly this reason. */
#include <nghttp3/version.h>
#include <nghttp3/nghttp3.h>

#endif /* NGNET_H3_SYS_WRAPPER_H */
