//! Raw FFI bindings to [libngtcp2](https://github.com/ngtcp2/ngtcp2), the QUIC
//! transport library from the ngtcp2 project.
//!
//! The native library is compiled from the `deps/ngtcp2` git submodule by this
//! crate's build script (lib-only, static). The bindings below are generated by
//! `bindgen` at build time, so they always match the vendored headers.
//!
//! ngtcp2 implements the QUIC transport only. It performs no I/O — it turns
//! datagrams into stream data and back, and leaves sending and receiving to the
//! caller — and it does not itself depend on a TLS library.
//!
//! # TLS
//!
//! QUIC needs a TLS handshake, but ngtcp2 does not link one. It instead ships a
//! *crypto helper* library per TLS backend, and this crate builds one of them,
//! for OpenSSL, behind the default-on `crypto-ossl` feature. Building with
//! `--no-default-features` links `libngtcp2.a` alone and pulls in no TLS at all.
//!
//! The OpenSSL helper needs OpenSSL 3.5 or newer, the first release carrying the
//! QUIC TLS API it is written against. Older OpenSSL, quictls and LibreSSL
//! expose a different API, for which ngtcp2 builds a *different* archive that
//! this crate does not link; the build script fails with an explanation rather
//! than letting that turn into a missing-symbol error.
//!
//! Two caveats worth knowing before building anything on the `ossl` backend,
//! both from upstream rather than from this crate:
//!
//! - It is still labelled **experimental**, unlike the BoringSSL, wolfSSL and
//!   GnuTLS helpers. Only one OpenSSL-family helper can be built at a time, so
//!   this is a choice between backends, not an addition to them.
//! - It imposes an ordering requirement the others do not, because the helper
//!   parks a pointer to its own state in the `SSL` object's app data. An
//!   application must ensure *either* that the `ngtcp2_conn` outlives the `SSL`
//!   object it is paired with, *or* that `SSL_set_app_data(ssl, NULL)` is called
//!   before `SSL_free`. Neither is enforced by these bindings; a safe wrapper
//!   has to own that ordering.
//!
//! (The transport parameter and crypto buffers OpenSSL borrows rather than
//! copies are ngtcp2's own bookkeeping, inside the helper, and not something a
//! caller has to arrange.)
//!
//! This is an unsafe, unopinionated `-sys` crate: it exposes the C API as-is.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(rustdoc::broken_intra_doc_links)]
// ngtcp2's own doxygen comments cite RFCs as bare URLs, and bindgen carries them through
// verbatim. Rewriting generated documentation to satisfy a lint would mean post-processing
// the bindings, which is a far worse trade than allowing the lint here.
#![allow(rustdoc::bare_urls)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
