#ifndef NGNET_QUIC_SYS_WRAPPER_H
#define NGNET_QUIC_SYS_WRAPPER_H

/* `version.h` is generated by CMake from `version.h.in`, so it exists only in
   the install tree. The build script points bindgen at the install include
   directory rather than at the source checkout for exactly this reason. */
#include <ngtcp2/version.h>
#include <ngtcp2/ngtcp2.h>

/* The crypto helper headers are only installed when a TLS backend was enabled,
   so including them unconditionally would break a `--no-default-features`
   build. The build script defines this to match the cargo feature. */
#ifdef NGNET_QUIC_SYS_CRYPTO_OSSL
#include <ngtcp2/ngtcp2_crypto.h>
/* Pulls in <openssl/ssl.h>, which is why the build script has to hand bindgen
   OpenSSL's include path as well as ngtcp2's. */
#include <ngtcp2/ngtcp2_crypto_ossl.h>
/* Not reached through <openssl/ssl.h>, but a TLS backend that cannot read the
   error queue can only report that a handshake failed, never why. */
#include <openssl/err.h>
/* The QUIC-TLS record layer's dispatch table. `<openssl/ssl.h>` declares
   `SSL_set_quic_tls_cbs` but not the `OSSL_DISPATCH` type or the function
   identifiers that populate it. */
#include <openssl/core_dispatch.h>
/* The crypto helper's internal header, which is compiled into the archive but
   not installed. It declares the QUIC key schedule --
   `ngtcp2_crypto_derive_initial_secrets`,
   `ngtcp2_crypto_derive_packet_protection_key`,
   `ngtcp2_crypto_hkdf_expand_label` -- along with the header protection cipher
   constructor and the AEAD usage limits.

   Using these is what keeps this crate out of the business of implementing the
   QUIC key schedule. Reimplementing it would be the single highest-risk part
   of supplying a TLS backend, because a subtly wrong salt or label produces two
   endpoints that agree with each other and with nobody else -- which every test
   in this repository would pass.

   Depending on a header the install step does not publish is a real cost, and
   is taken deliberately. It is bounded by the submodule being pinned, and by
   bindgen reading the actual declarations rather than a restatement of them, so
   a signature that changes upstream is a compile error rather than a silent
   argument mismatch. `versioned_ffi.rs` already sets this precedent for a
   constant restated from a private ngtcp2 header, and pins it with a test. */
#include <shared.h>
#endif

/* ---------------------------------------------------------------------------
   Constants bindgen cannot evaluate on its own.

   ngtcp2 writes its integer macros with a cast — `((uint32_t)0x1U)`,
   `((ngtcp2_duration)(1000ULL * NGTCP2_MICROSECONDS))` — and bindgen's macro
   evaluator gives up on those, silently. Silently is the problem: nothing warns,
   the constant is simply absent, and it is only missed at the point some
   wrapper needs it. Eleven constants were dropped this way, among them every
   time unit and the protocol version, which between them are needed to build
   any connection at all.

   Each is restated below without the cast so that bindgen can evaluate it, and
   each restatement is pinned to the header's own value by a _Static_assert. A
   value that ever diverges is a compile error naming the constant, rather than
   a wrong number that type-checks. The #undef only affects this file, which
   nothing but bindgen includes.

   The values are given plain integer literals; the Rust type each one gets is
   pinned in build.rs, not here. bindgen sizes an integer macro by its *value*
   rather than by its suffix, so `1000000000ULL` still arrives as a u32 — see
   `DurationTypes` in build.rs for why that would be the wrong type.
   --------------------------------------------------------------------------- */

_Static_assert(NGTCP2_NANOSECONDS == 1ULL, "NGTCP2_NANOSECONDS changed");
#undef NGTCP2_NANOSECONDS
#define NGTCP2_NANOSECONDS 1ULL

_Static_assert(NGTCP2_MICROSECONDS == 1000ULL, "NGTCP2_MICROSECONDS changed");
#undef NGTCP2_MICROSECONDS
#define NGTCP2_MICROSECONDS 1000ULL

_Static_assert(NGTCP2_MILLISECONDS == 1000000ULL, "NGTCP2_MILLISECONDS changed");
#undef NGTCP2_MILLISECONDS
#define NGTCP2_MILLISECONDS 1000000ULL

_Static_assert(NGTCP2_SECONDS == 1000000000ULL, "NGTCP2_SECONDS changed");
#undef NGTCP2_SECONDS
#define NGTCP2_SECONDS 1000000000ULL

_Static_assert(NGTCP2_MINUTES == 60000000000ULL, "NGTCP2_MINUTES changed");
#undef NGTCP2_MINUTES
#define NGTCP2_MINUTES 60000000000ULL

_Static_assert(NGTCP2_DEFAULT_INITIAL_RTT == 333000000ULL,
               "NGTCP2_DEFAULT_INITIAL_RTT changed");
#undef NGTCP2_DEFAULT_INITIAL_RTT
#define NGTCP2_DEFAULT_INITIAL_RTT 333000000ULL

_Static_assert(NGTCP2_DEFAULT_MAX_ACK_DELAY == 25000000ULL,
               "NGTCP2_DEFAULT_MAX_ACK_DELAY changed");
#undef NGTCP2_DEFAULT_MAX_ACK_DELAY
#define NGTCP2_DEFAULT_MAX_ACK_DELAY 25000000ULL

_Static_assert(NGTCP2_PROTO_VER_V1 == 0x00000001u, "NGTCP2_PROTO_VER_V1 changed");
_Static_assert(NGTCP2_PROTO_VER_V2 == 0x6b3343cfu, "NGTCP2_PROTO_VER_V2 changed");
/* MIN and MAX are aliases of V1 today. They are restated as their own literals
   rather than left to expand through V1, so that if upstream ever widens the
   supported range the assertion fires instead of the alias quietly following. */
_Static_assert(NGTCP2_PROTO_VER_MAX == 0x00000001u, "NGTCP2_PROTO_VER_MAX changed");
_Static_assert(NGTCP2_PROTO_VER_MIN == 0x00000001u, "NGTCP2_PROTO_VER_MIN changed");
#undef NGTCP2_PROTO_VER_V1
#undef NGTCP2_PROTO_VER_V2
#undef NGTCP2_PROTO_VER_MAX
#undef NGTCP2_PROTO_VER_MIN
#define NGTCP2_PROTO_VER_V1 0x00000001u
#define NGTCP2_PROTO_VER_V2 0x6b3343cfu
#define NGTCP2_PROTO_VER_MAX 0x00000001u
#define NGTCP2_PROTO_VER_MIN 0x00000001u

#endif /* NGNET_QUIC_SYS_WRAPPER_H */
